# all roles
GET http://localhost:8080/api/v1/roles

###
# one role
GET http://localhost:8080/api/v1/roles/3

###
# all users
GET http://localhost:8080/api/v1/users

###
# one user
GET http://localhost:8080/api/v1/users/2

###
# register as normal user
POST http://localhost:8080/api/v1/session/register
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "johndoe@example.co",
    "phone": "9999999999",
    "password": "lolwth@4"
}

###
# register as admin user
POST http://localhost:8080/api/v1/session/register
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Admin",
    "email": "youremail2@title.com",
    "phone": "9999999999",
    "password": "lolwth@4"
}

###
# activate account
POST http://localhost:8080/api/v1/session/account/activate
Content-Type: application/json

{
    "email": "johndoe@example.co",
    "code": "24734641"
}

###
# next request must be activate account 
POST http://localhost:8080/api/v1/session/account/reverify
Content-Type: application/json

{
    "email": "johndoe@example.co",
    "phone": "9999999999"
}

###
# forgot password
POST  http://localhost:8080/api/v1/session/password/forgot
Content-Type: application/json

{
    "email": "johndoe@example.co"
}

###
# reset password
POST http://localhost:8080/api/v1/session/password/reset/:id/:token
Content-Type: application/json

{
    "password": "lolwth@3"
}

###
# login
POST  http://localhost:8080/api/v1/session/login
Content-Type: application/json

{
    "email": "johndoe@example.co",
    "password": "lolwth@3"
}

###
# my profile
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json


###
# refresh-token
POST  http://localhost:8080/api/v1/session/tokens/refresh
Content-Type: application/json


###
# change password
POST http://localhost:8080/api/v1/users/password/change
Content-Type: application/json

{
    "current_password": "lolwth@3",
    "new_password": "lolwth@4"
}

###
# logout
POST  http://localhost:8080/api/v1/session/logout
Content-Type: application/json
